### ISSUE TITLE
🐛 Bug Report: Some icons from heroicons dont work

### ISSUE THREAD

**Issue by probablyArth** [appwrite/pink#76] opened 2023-04-09 17:45 UTC
### 👟 Reproduction steps

- `"@appwrite.io/pink-icons"` to your project
- use `<div class="icon-login"></div>`

### 👍 Expected behavior

this icon should appear
![image](https://user-images.githubusercontent.com/61962871/230787867-686a31a5-d434-41f9-983e-12447aa11b91.png)

### 👎 Actual Behavior

It's an empty div

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

@appwrite.io/pink - 0.0.6-rc.9

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment] 2023-04-10 17:10
Thank you for reporting this issue.

**Comment by joeyouss** [comment] 2023-04-11 09:52
Hi @probablyArth - our team is looking into fixing this, thank you for reporting!

**Comment by goswamianshuman** [comment] 2023-04-27 08:49
Hello, If the issue is not assigned to someone so can  I try to fix it please.

**Closed** 2023-05-04 11:20 UTC
Labels: bug
